### ISSUE TITLE
Adding manual commands to the job

### ISSUE THREAD

**Issue by ScheiklP** [ALRhub/clusterduck#8]
In my setup, I need to execute some bash commands before actually starting the training.
For example sourcing the bashrc, activating the conda environment, etc.
Is there a way to tell the job "please run this sh script, before running python3 script.py"?

**Comment by nicolas-schreiber** [comment]
In the hydra->launcher dict you could add a list called `setup` with the bash commands for fully setting up your environment.

For reference: 
https://hydra.cc/docs/plugins/submitit_launcher/
https://github.com/facebookincubator/submitit/blob/83898f0a3d9d20a2d5efbc215a3e4d708701f3c4/submitit/slurm/slurm.py#L498C15-L498C15

**Comment by ScheiklP** [comment]
So that would be something like:

```
hydra:
   launcher:
      setup:
         - "source $HOME/.bashrc"
         - "conda activate sofa"
```
?
